services:
  - type: web
    name: my-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn Real_Portfolio.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
